### ISSUE TITLE
Certificate Errors 

### ISSUE THREAD

**Issue by TechyBee** [XamarinUniversity/XAM120#2]
Hello! I am seeing many certificate errors when I build my projects and it's all coming from Phoneword.UWP. 2 Errors I notice are the Certificate file 'Phoneword.UWP_TemporaryKey.pfx' not found, and The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478. It should build and run as expected, but it's throwing 
these errors instead. Currently, I am running the new Windows 10 version 1807, and Visual Studio Community 2017 version 15.7.5.

Alongside with these certificate errors, Xamarin.Forms isn't matching the targets. and Xamarin.Forms is up to date on all platforms, and my android emulator will not let the app run either. Running Oreo Android OS on my emulator API 27. This API Seems to give me issues all the time just so you know.

Help would be appreciated!

Thanks!

**Comment by patridge** [comment]
Sorry about that key issue. Our default .gitignore setup (which decides which files to maintain in source control) is a little overzealous about omitting those _TemporaryKey.pfx files. While they shouldn't be absolutely necessary, we prefer to include them with exercises for simplicity.

That particular file is just a developer test key for signing the app to install on Windows. If you were publishing an app in the real world, you might want something more official. For these exercises, though, they work just fine.

Until then, if you generate a new Xamarin.Forms project in Visual Studio with UWP support, you should get one automatically. They are generated as part of the project creation. Additionally, you can [generate a new test key](https://stackoverflow.com/a/35478067/48700) on your machine as well.

As for the "matching the targets" issue you mention, I'm not sure I follow. It sounds like a Xamarin issue of some sort rather than an issue with this course, though. Are you getting any error messages that might help diagnose where the problem is? If you have some specifics, it might help track down the issue you are encountering on the [forums](https://forums.xamarin.com/).

**Comment by patridge** [comment]
@TechyBee I've pushed up some new dev keys to the exercise 2 and 3 UWP projects. If you are still seeing the issue, let me know.

**Comment by TechyBee** [comment]
@patridge Hello! Creating that new dev key seemed to clear up the targets not matching and I am no longer getting the certificate issues anymore. Thanks!

**Comment by TechyBee** [comment]
@patridge Unfortunately, Android is down. It's saying that 'Build Failed: Xamarin.Android does not support running the previous version.  Please ensure your solution builds before running or debugging it.' when in reality, I've already built the project. Happens with me all the time so I have to use a lower API.
